### ISSUE TITLE
Automated Daily Login

### ISSUE THREAD

**Issue by audiopathik** [thomas-ashcraft/alienware_arena_helper#10]
Hi!

Amazing tool, thanks for your work!

Maybe it was possible to integrate automated daily login/visit for the consecutive ARP points?

Thanks a lot!

**Comment by thomas-ashcraft** [comment]
I'm glad you found this script useful.

To be honest it is already in gray area. AWA admins mostly keeping a blind eye for this script, but only while it not interfere with site working and purposes. Since main purpose of AWA site is provide info about Alienware products and attract to them as many people as possible through site visits, fully automated site visiting will be interference to AWA purposes. So I will not dare to implement such function in this particular script. Especially since I'm really in love with  Alienware notebooks and want them to be as much popular as possible.

Another reason to avoid such functionality is that constantly repeating daily work is not task for browsers nor for the frontend enhacement scripts. This functionality is more suitable to be done by the backend script.

**Comment by audiopathik** [comment]
Thanks for your response, by now visiting Alienware Arena, doing the daily quest and choosing 5 attractive pictures for upvotes has become a daily routine!

Most online portals treat bots and automated scripts this way, especially when it comes to bargain or rewards, therefor I was expecting this answer and completely understand this, as it is sustained by people visiting their and their affiliates' contents and abuse of this system would ultimately lead to the closure of the Alienware Arena online portal, which is the opposite of what I am after, even though I am an Acer Predator user currently.
