### ISSUE TITLE
Not working on ARP 6.0

### ISSUE THREAD

**Issue by Mishasama** [thomas-ashcraft/alienware_arena_helper#28]
Any update?

**Comment by Lucki** [comment]
I don't think it's worth pushing this script further. It already lost some functionality when the site was updated before and would need some serious rework again because the quest names aren't published anymore.

There is however a new script which builds upon a community driven API to distribute said quest names: https://codeberg.org/Sudo/AlienwareArena-Auto-Daily-Quests

> [**Feel free to use it in other AWA related projects!**](https://codeberg.org/Sudo/AlienwareArena-Auto-Daily-Quests#rest-api)

Reporting unrecognized quest seems rather technical sadly - I'm sure some user feedback would be appreciated to improve there:
> [Because sharing is caring! Help to keep the API up to date with the new quests.](https://codeberg.org/Sudo/AlienwareArena-Auto-Daily-Quests#reporting-new-quests)

**Comment by Mishasama** [comment]
> There is however a new script which builds upon a community driven API to distribute said quest names: https://codeberg.org/Sudo/AlienwareArena-Auto-Daily-Quests

Thank you! It looks works well!
